### ISSUE TITLE
Kick T4g1

### ISSUE THREAD

**Issue by Paglops** [T4g1/z14#15]
## Objective
Give back the power to users by providing them with fair ways to fight back abusive authority.

## Features

- Keep track of how many times the command was used in the last 24hours
- How much time T4g1 spent muted in the last 24hours
- Mute T4g1 for an arbitrary amount of time
- Unmute T4g1 when the timer expires
- Refuses any subsequent kt while T4g1 is muted by the command
- Detects if T4g1 is in a vocal channel

Related to #5 #7 

## Command
.kt

**Comment by T4g1** [comment]
Worst idea ever, 0/10 no effort put into this trash

**Comment by Paglops** [comment]
I take your comment and .o 
All the best,
Paglops

**Comment by T4g1** [comment]
This is against our policies, im afraid your idea is shit. Best regards

**Comment by Paglops** [comment]
Hi,
As included the body of the request, issues #5 and #7 are highly similar to this one. Does this means that your policies only apply to you?
This seems a bit not nice imho.
All the best,
