### ISSUE TITLE
Poll features - z14 improvement 

### ISSUE THREAD

**Issue by Paglops** [T4g1/z14#39]
## Objective
Provide users will the ability to poll a channel.

## Features
**Single-choice poll**
1. User inputs question only
>.poll "Do you wanna marry me?"
>.z14: Do you wanna marry me? 
✅ Yes
❌ No
People can answer by clicking one of the emojis (see References section)

2. User inputs question and 2 choices
>.poll "What do you prefer?" "Tomatoes" "Cucumbers"
>.z14: What do you prefer? 
1️⃣ Tomatoes
2️⃣ Cucumber

**Multi-choices poll**
User inputs question and ]2;9] choices.
>.poll "Do you have a boyfriend?" "Yes" "It's complicated" "No"
>.z14: Do you have a boyfriend? 
1️⃣ Yes
2️⃣ It's complicated
3️⃣ No

## Commands
Single choice poll
>.poll "_question_"
>.poll "_question_" "_Choice 1_" "_Choice 2_"

Multi-choices poll
>.poll "_question_" "_Choice 1_" "_Choice 2_" "_Choice 3_" ... "_Choice n_"

## References
Simple poll (Slack) https://simplepoll.rocks/
Polly (Slack) https://www.polly.ai/

**Comment by T4g1** [comment]
* Users vote using emotes
* Bot creates two messages: Vote message and results message directly beneath it
* Bot updates stats messages depending on vote message's emotes

**Comment by Paglops** [comment]
**SEND BACK TO DEV** - Not compliant with original ticket. 
Please ensure to QA your own work before pushing to prod & notify appropriate stakeholders for review.

Thanks! ✨

**Comment by Laufral** [comment]
Hey guys!
That would be great if we could somehow specify as an argument an option to make to poll mono or multichoice.
Thank you
