### ISSUE TITLE
Hydratation reminder

### ISSUE THREAD

**Issue by lcoenen** [T4g1/z14#42]
**Definition of done**

- The bot emit a message every two hours reminding everybody to drink water.

See also: r/hydrohomies

https://www.reddit.com/r/HydroHomies/
![image](https://user-images.githubusercontent.com/1237971/106942666-5eabe180-671c-11eb-8551-1f882d853abc.png)

**Comment by T4g1** [comment]
Hyper chaud

**Comment by T4g1** [comment]
Issue 42!
