### ISSUE TITLE
Bug in kick_malabar

### ISSUE THREAD

**Issue by bendardenne** [T4g1/z14#5]
There is currently a bug in the bot wherein malabar gets muted for 5 seconds instead of the expected 5 minutes when using the kick malabar command.
Please fix this issue ASAP, this is impacting our productivity.

**Comment by T4g1** [comment]
Some users have reported significant productivity improvements when using the following technic: ![2021-01-28 14_22_44-🏢 Coworking](https://user-images.githubusercontent.com/1417856/106144326-554ad400-6174-11eb-8fc1-ac430caa3921.png)

The z14 staff urges you to use that workaround whenever possible while we are trying our best to adress the issue ASAP
