### ISSUE TITLE
Improvement request: on friday night, hydro feature should source from r/beermemes

### ISSUE THREAD

**Issue by lcoenen** [T4g1/z14#53]
**Definition of done**:

☐ On friday night from 20:00 UTC to midnight of the same day, z14 should source memes from r/beermemes instead of r/hydrohomies.
☐ Normal behavior should resume at any other time

**Illustration:**

![image](https://user-images.githubusercontent.com/1237971/107830066-f6e04100-6d82-11eb-9478-212947c7933d.png)

**Comment by T4g1** [comment]
Will use beerporn
